FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY FoodTruck.Api/*.csproj ./FoodTruck.Api/
RUN dotnet restore ./FoodTruck.Api/FoodTruck.Api.csproj
COPY . .
RUN dotnet publish FoodTruck.Api/FoodTruck.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FoodTruck.Api.dll"]