services:
  api:
    build:
      context: ./FoodTruck.Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "FoodTruck.Api.dll"]

  web:
    build:
      context: ./FoodTruck.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api